# Generated by Django 2.1.3 on 2018-11-29 00:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculo', '0001_initial'),
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, unique=True)),
                ('descricao', models.TextField(blank=True, default=None, max_length=500, null=True)),
                ('conteudo', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=20)),
                ('extras', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contas.Professor')),
            ],
        ),
        migrations.CreateModel(
            name='AtividadeVinculada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rotulo', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=20)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restrito.Atividade')),
                ('disciplina_ofertada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='curriculo.DisciplinaOfertada')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contas.Professor')),
            ],
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('resposta', models.TextField(max_length=500)),
                ('data_entrega', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('status', models.CharField(blank=True, default='Entregue', max_length=20, null=True)),
                ('nota', models.DecimalField(decimal_places=2, max_digits=5)),
                ('data_avaliacao', models.DateTimeField(blank=True, default=None, null=True)),
                ('obs', models.TextField(max_length=500)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contas.Aluno')),
                ('atividade_vinculada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restrito.AtividadeVinculada')),
                ('professor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='contas.Professor')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitacaoMatricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('status', models.CharField(blank=True, choices=[('Solicitada', 'Solicitada'), ('Aprovada', 'Aprovada'), ('Reprovada', 'Reprovada')], default='Solicitada', max_length=50, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contas.Aluno')),
                ('coordenador', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='contas.Coordenador')),
                ('disciplina_ofertada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='curriculo.DisciplinaOfertada')),
            ],
            options={
                'verbose_name': 'solicitação de matrícula',
                'verbose_name_plural': 'solicitações de matrícula',
            },
        ),
        migrations.AlterUniqueTogether(
            name='entrega',
            unique_together={('aluno', 'atividade_vinculada')},
        ),
        migrations.AlterUniqueTogether(
            name='atividadevinculada',
            unique_together={('atividade', 'disciplina_ofertada', 'rotulo')},
        ),
    ]
