# Generated by Django 2.1.3 on 2018-12-05 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restrito', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='tipo',
            field=models.CharField(choices=[('RESPOSTA ABERTA', 'Resposta Aberta'), ('TESTE', 'Teste')], max_length=20),
        ),
    ]
