# Generated by Django 2.1.3 on 2018-11-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restrito', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitacaomatricula',
            options={'verbose_name': 'solicitação de matrícula', 'verbose_name_plural': 'solicitações de matrícula'},
        ),
        migrations.AlterField(
            model_name='solicitacaomatricula',
            name='status',
            field=models.CharField(blank=True, choices=[('Solicitada', 'Solicitada'), ('Aprovada', 'Aprovada'), ('Reprovada', 'Reprovada')], default='Solicitada', max_length=50, null=True),
        ),
    ]
