# Generated by Django 2.1.3 on 2018-12-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restrito', '0003_auto_20181204_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividadevinculada',
            name='status',
            field=models.CharField(choices=[('DISPONIBILIZADA', 'Disponibilizada'), ('ABERTA', 'Aberta'), ('FECHADA', 'Fechada'), ('ENCERRADA', 'Encerrada'), ('PRORROGADA', 'Prorrogada')], max_length=20),
        ),
    ]
