# Generated by Django 2.1.3 on 2018-12-07 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restrito', '0005_auto_20181207_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrega',
            name='nota',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
