# Generated by Django 2.1.3 on 2018-12-12 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restrito', '0006_auto_20181207_1834'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entrega',
            options={'ordering': ['aluno']},
        ),
        migrations.AlterField(
            model_name='entrega',
            name='status',
            field=models.CharField(blank=True, choices=[('ENTREGUE', 'Entregue'), ('CORRIGIDO', 'Corrigido')], default='ENTREGUE', max_length=20, null=True),
        ),
    ]
