# Generated by Django 2.1.3 on 2018-11-29 00:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(max_length=255)),
                ('referencia', models.CharField(max_length=255)),
                ('conteudo', models.TextField(max_length=500)),
                ('status', models.CharField(blank=True, default='Enviada', max_length=100, null=True)),
                ('data_envio', models.DateField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('data_resposta', models.DateField(blank=True, default=None, null=True)),
                ('resposta', models.TextField(blank=True, default=None, max_length=500, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.Aluno')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contas.Professor')),
            ],
        ),
    ]
