# Generated by Django 2.1.3 on 2018-11-16 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('login', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(db_column='senha', max_length=128, verbose_name='Senha')),
                ('dt_expiracao', models.DateField(blank=True, default=datetime.date(1900, 1, 1), null=True)),
                ('tipo', models.CharField(choices=[('C', 'Coordenador'), ('P', 'Professor'), ('A', 'Aluno')], max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
