# Generated by Django 2.1.3 on 2018-11-16 13:36

import contas.models.usuarios
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', contas.models.usuarios.UsuarioManager()),
            ],
        ),
    ]
