# Generated by Django 2.1.3 on 2018-11-16 14:41

import contas.models.usuarios
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_auto_20181116_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordenador',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nome', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('celular', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('contas.usuario',),
            managers=[
                ('objects', contas.models.usuarios.UsuarioManager()),
            ],
        ),
    ]
