# Generated by Django 2.1.3 on 2018-11-18 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_coordenador'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coordenador',
            options={'verbose_name': 'coordenador', 'verbose_name_plural': 'coordenadores'},
        ),
    ]
