# Generated by Django 2.1.3 on 2018-11-18 00:43

import contas.models.usuarios
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0004_auto_20181117_2242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nome', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('celular', models.CharField(max_length=20, unique=True)),
                ('apelido', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'professor',
                'verbose_name_plural': 'professores',
            },
            bases=('contas.usuario',),
            managers=[
                ('objects', contas.models.usuarios.UsuarioManager()),
            ],
        ),
    ]
