# Generated by Django 2.1.3 on 2018-11-20 23:27

import contas.models.alunos
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0006_aluno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=contas.models.alunos.diretorio_aluno),
        ),
    ]
