# Generated by Django 2.1 on 2018-11-07 10:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100, unique=True)),
                ('senha', models.CharField(max_length=100)),
                ('dt_expiracao', models.DateField(blank=True, default=datetime.date(1900, 1, 1), null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lms.Usuario')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('celular', models.CharField(max_length=20, unique=True)),
                ('ra', models.CharField(max_length=20, unique=True)),
                ('foto', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
            bases=('lms.usuario',),
        ),
        migrations.CreateModel(
            name='Coordenador',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lms.Usuario')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('celular', models.CharField(max_length=20, unique=True)),
            ],
            bases=('lms.usuario',),
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lms.Usuario')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('celular', models.CharField(max_length=20, unique=True)),
                ('apelido', models.CharField(max_length=255)),
            ],
            bases=('lms.usuario',),
        ),
    ]
