# Generated by Django 2.1.3 on 2018-11-10 10:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_auto_20181107_0849'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, unique=True)),
                ('descricao', models.TextField(blank=True, default=None, max_length=500, null=True)),
                ('conteudo', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=20)),
                ('extras', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.Professor')),
            ],
        ),
        migrations.CreateModel(
            name='AtividadeVinculada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rotulo', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=20)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.Atividade')),
                ('disciplina_ofertada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.DisciplinaOfertada')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.Professor')),
            ],
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('resposta', models.TextField(max_length=500)),
                ('status', models.CharField(blank=True, default='Entregue', max_length=20, null=True)),
                ('nota', models.DecimalField(decimal_places=2, max_digits=5)),
                ('data_entrega', models.DateTimeField(blank=True, default=None, null=True)),
                ('obs', models.TextField(max_length=500)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.Aluno')),
                ('atividade_vinculada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.AtividadeVinculada')),
                ('professor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='lms.Professor')),
            ],
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='data',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='solicitacaomatricula',
            name='data',
            field=models.DateField(blank=True, default=django.utils.timezone.now, editable=False, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='entrega',
            unique_together={('aluno', 'atividade_vinculada')},
        ),
        migrations.AlterUniqueTogether(
            name='atividadevinculada',
            unique_together={('atividade', 'disciplina_ofertada', 'rotulo')},
        ),
    ]
