# Generated by Django 2.1.3 on 2018-11-10 10:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_auto_20181110_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='data_avaliacao',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='data_entrega',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True),
        ),
    ]
