# Generated by Django 2.1.3 on 2018-11-20 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20181119_2251'),
        ('lms', '0005_usuario_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='usuario_ptr',
        ),
        migrations.RemoveField(
            model_name='coordenador',
            name='usuario_ptr',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='usuario_ptr',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='user',
        ),
        migrations.AlterField(
            model_name='atividade',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contas.Professor'),
        ),
        migrations.AlterField(
            model_name='atividadevinculada',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contas.Professor'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='coordenador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contas.Coordenador'),
        ),
        migrations.AlterField(
            model_name='disciplinaofertada',
            name='coordenador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contas.Coordenador'),
        ),
        migrations.AlterField(
            model_name='disciplinaofertada',
            name='professor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='contas.Professor'),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contas.Aluno'),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='professor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='contas.Professor'),
        ),
        migrations.AlterField(
            model_name='solicitacaomatricula',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contas.Aluno'),
        ),
        migrations.AlterField(
            model_name='solicitacaomatricula',
            name='coordenador',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='contas.Coordenador'),
        ),
        migrations.DeleteModel(
            name='Aluno',
        ),
        migrations.DeleteModel(
            name='Coordenador',
        ),
        migrations.DeleteModel(
            name='Professor',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
