# Generated by Django 2.1.3 on 2018-11-27 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_auto_20181119_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplina',
            name='coordenador',
        ),
        migrations.AlterUniqueTogether(
            name='disciplinaofertada',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='disciplinaofertada',
            name='coordenador',
        ),
        migrations.RemoveField(
            model_name='disciplinaofertada',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='disciplinaofertada',
            name='disciplina',
        ),
        migrations.RemoveField(
            model_name='disciplinaofertada',
            name='professor',
        ),
        migrations.RemoveField(
            model_name='disciplinaofertada',
            name='turma',
        ),
        migrations.RemoveField(
            model_name='solicitacaomatricula',
            name='aluno',
        ),
        migrations.RemoveField(
            model_name='solicitacaomatricula',
            name='coordenador',
        ),
        migrations.RemoveField(
            model_name='solicitacaomatricula',
            name='disciplina_ofertada',
        ),
        migrations.DeleteModel(
            name='Turma',
        ),
        migrations.AlterField(
            model_name='atividadevinculada',
            name='disciplina_ofertada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='curriculo.DisciplinaOfertada'),
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.DeleteModel(
            name='Disciplina',
        ),
        migrations.DeleteModel(
            name='DisciplinaOfertada',
        ),
        migrations.DeleteModel(
            name='SolicitacaoMatricula',
        ),
    ]
