# Generated by Django 2.1.3 on 2018-11-27 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0007_auto_20181127_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='professor',
        ),
        migrations.AlterUniqueTogether(
            name='atividadevinculada',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='atividadevinculada',
            name='atividade',
        ),
        migrations.RemoveField(
            model_name='atividadevinculada',
            name='disciplina_ofertada',
        ),
        migrations.RemoveField(
            model_name='atividadevinculada',
            name='professor',
        ),
        migrations.AlterUniqueTogether(
            name='entrega',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='entrega',
            name='aluno',
        ),
        migrations.RemoveField(
            model_name='entrega',
            name='atividade_vinculada',
        ),
        migrations.RemoveField(
            model_name='entrega',
            name='professor',
        ),
        migrations.DeleteModel(
            name='Atividade',
        ),
        migrations.DeleteModel(
            name='AtividadeVinculada',
        ),
        migrations.DeleteModel(
            name='Entrega',
        ),
    ]
