# Generated by Django 2.1.3 on 2018-11-29 00:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('sigla', models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('data', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('status', models.CharField(blank=True, default='Aberta', max_length=50, null=True)),
                ('plano_ensino', models.TextField(max_length=500)),
                ('carga_horaria', models.IntegerField()),
                ('competencias', models.TextField(max_length=500)),
                ('habilidades', models.TextField(max_length=500)),
                ('ementa', models.TextField(max_length=500)),
                ('conteudo_programatico', models.TextField(max_length=500)),
                ('bibliografia_basica', models.TextField(max_length=500)),
                ('bibliografia_complementar', models.TextField(max_length=500)),
                ('percentual_pratico', models.IntegerField()),
                ('percentual_teorico', models.IntegerField()),
                ('coordenador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contas.Coordenador')),
            ],
        ),
        migrations.CreateModel(
            name='DisciplinaOfertada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_inicio_matricula', models.DateField()),
                ('dt_fim_matricula', models.DateField()),
                ('metodologia', models.TextField(blank=True, default=None, max_length=500, null=True)),
                ('recursos', models.TextField(blank=True, default=None, max_length=500, null=True)),
                ('criterio_avaliacao', models.TextField(blank=True, default=None, max_length=500, null=True)),
                ('plano_aulas', models.TextField(blank=True, default=None, max_length=500, null=True)),
                ('coordenador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contas.Coordenador')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='curriculo.Curso')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='curriculo.Disciplina')),
                ('professor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='contas.Professor')),
            ],
            options={
                'verbose_name': 'oferta de disciplina',
                'verbose_name_plural': 'ofertas de disciplinas',
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('semestre', models.IntegerField()),
                ('nome', models.CharField(max_length=1)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='turma',
            unique_together={('ano', 'semestre', 'nome')},
        ),
        migrations.AddField(
            model_name='disciplinaofertada',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='curriculo.Turma'),
        ),
        migrations.AlterUniqueTogether(
            name='disciplinaofertada',
            unique_together={('disciplina', 'curso', 'turma')},
        ),
    ]
