# Generated by Django 2.1.3 on 2018-11-28 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0002_auto_20181127_1945'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disciplinaofertada',
            options={'verbose_name': 'oferta de disciplina', 'verbose_name_plural': 'ofertas de disciplinas'},
        ),
    ]
